language: python 

os:
  - linux

branches:
  only:
    - master
    - /^(dev)|(dev_.*)$/

python:
  - "3.5"
  - "3.6"

install:
  - pip install -U -r requirements.txt

script:
  - python -m pytest -v --ignore=tests/gui/
